./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/400.perlbench-50B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/401.bzip2-226B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/403.gcc-16B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/410.bwaves-1963B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/416.gamess-875B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/433.milc-337B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/434.zeusmp-10B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/435.gromacs-111B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/436.cactusADM-1804B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/437.leslie3d-149B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/444.namd-426B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/445.gobmk-30B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/447.dealII-3B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/450.soplex-247B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/453.povray-576B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/454.calculix-460B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/456.hmmer-88B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/458.sjeng-767B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/459.GemsFDTD-1491B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/462.libquantum-714B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/464.h264ref-97B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/465.tonto-1769B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/470.lbm-1274B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/473.astar-42B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/481.wrf-196B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/482.sphinx3-417B.trace.gz
./exclusiu /media/kevin/EXTERNAL/apex-proj/traces/483.xalancbmk-127B.trace.gz
